name: "âš™ï¸ C++ CI Workflow with conda-forge dependencies"

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'  #  Nightly build

jobs:
  build:
    name: "ğŸ”¨ [${{ matrix.os }}@${{ matrix.build_type }}@conda]"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        channels: conda-forge,robostack-jazzy
        channel-priority: true

    - name: "ğŸ“š Install Dependencies"
      shell: bash -l {0}
      run: |
        # Workaround for ğŸ”§ https://github.com/conda-incubator/setup-miniconda/issues/186
        conda config --remove channels defaults
        # Dependencies
        conda install cmake compilers make ninja pkg-config \
                      "soem>=2.0.0" yarp

    - name: "ğŸ” Print used environment"
      shell: bash -l {0}
      run: |
        conda list
        env

    - name: "âš™ï¸ Configure [Linux & macOS]"
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        mkdir -p build
        cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

    - name: "ğŸ—ï¸ Build [Linux & macOS]"
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}
